trigger:
- master

pool:
  vmImage: 'macOS-latest'

steps:
- script: |
    npm i -g typescript && echo no | npm i -g nativescript && tns usage-reporting disable && tns error-reporting disable && npm i && tsc
    sudo pip install --upgrade pip && sudo pip install six
  displayName: 'Base Setup for NativeScript Builds'

- script: |
    cd demo && tns build ios --env.uglify
  displayName: 'iOS Build'

- script: |
    cd demo && tns build android --env.uglify
  displayName: 'Android Build'

- task: CopyFiles@1
  inputs:
    contents: '**/*'
    targetFolder: '$(build.artifactStagingDirectory)'