# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'macOS-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    npm run ci.base.setup
    npm run ci.pip.install
  displayName: 'Base Setup for CLI'

- script: |
    npm run ci.vanilla.ios.build
  displayName: 'iOS Build'
