name: Build CI

# Trigger the workflow on push
on: [push]

jobs:
  job1:
    name: Android Builds & Test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Base Setup
        run: npm run ci.base.setup

      - name: Lint
        run: npm run ci.tslint

      - name: Build Vanilla Android Demo App
        run: npm run ci.vanilla.android.build

      - name: Setup Android
        run: |
          echo "y" | $ANDROID_HOME/tools/bin/sdkmanager --install 'system-images;android-27;google_apis;x86'
          echo "no" | $ANDROID_HOME/tools/bin/avdmanager create avd -n test -k 'system-images;android-27;google_apis;x86' --force
          $ANDROID_HOME/emulator/emulator -list-avds
          $ANDROID_HOME/platform-tools/adb devices
      - name: Android Test
        run: |
          emulator -avd test -no-audio -no-window &
          android-wait-for-emulator
          cd src && npm i && npm run tsc && cd ../demo && tns build android
          tns test android --justlaunch

  job2:
    name: iOS Builds & Test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1

      - name: Base Setup
        run: npm run ci.base.setup && npm run ci.pip.install

      - name: Build Vanilla iOS Demo App
        run: npm run ci.vanilla.ios.build

      - name: iOS Test
        run: |
          cd src && npm i && npm run tsc && cd ../demo && tns build ios
          tns test ios --justlaunch
